"""可复用界面组件（Deep Telemetry 设计系统）。"""

from app.ui.widgets.cards import (
    Badge,
    KpiCard,
    ModuleCard,
    Pill,
    SectionCard,
    SegmentBar,
    StatRow,
    StatusDot,
    build_kpi_row,
    caption_label,
    chip,
    hint_label,
    horizontal_line,
    hstack,
    muted_label,
    section_label,
    vstack,
)
from app.ui.widgets.charts import (
    FunnelBars,
    MiniBars,
    PlatformBarChart,
    SentimentBar,
    SentimentPie,
    TopicCloud,
    TrendChart,
    WordCloudWidget,
)
from app.ui.widgets.tables import (
    ACCOUNT_COLUMNS,
    ANOMALY_COLUMNS,
    VIDEO_COLUMNS,
    Column,
    DictTableModel,
    PlatformBadgeDelegate,
    configure_table,
)

__all__ = [
    "Badge",
    "KpiCard",
    "ModuleCard",
    "Pill",
    "SectionCard",
    "SegmentBar",
    "StatRow",
    "StatusDot",
    "build_kpi_row",
    "caption_label",
    "chip",
    "hint_label",
    "horizontal_line",
    "hstack",
    "muted_label",
    "section_label",
    "vstack",
    "FunnelBars",
    "MiniBars",
    "PlatformBarChart",
    "SentimentBar",
    "SentimentPie",
    "TopicCloud",
    "TrendChart",
    "WordCloudWidget",
    "ACCOUNT_COLUMNS",
    "ANOMALY_COLUMNS",
    "VIDEO_COLUMNS",
    "Column",
    "DictTableModel",
    "PlatformBadgeDelegate",
    "configure_table",
]
