"""可复用界面组件（Deep Telemetry 设计系统）。"""

from app.ui.widgets.ai_chat import QUICK_QUESTIONS, AiChatPanel
from app.ui.widgets.insight_card import InsightBriefCard
from app.ui.widgets.cards import (
    Badge,
    KpiCard,
    ModuleCard,
    Pill,
    SectionCard,
    SegmentBar,
    StatRow,
    StatusDot,
    build_kpi_row,
    caption_label,
    chip,
    hint_label,
    horizontal_line,
    hstack,
    muted_label,
    section_label,
    vstack,
)
from app.ui.widgets.charts import (
    FunnelBars,
    MiniBars,
    PlatformBarChart,
    SentimentBar,
    SentimentPie,
    TopicCloud,
    TrendChart,
    WordCloudWidget,
)
from app.ui.widgets.responsive import PageScrollArea, ResponsiveKpiRow, ResponsiveSplitter
from app.ui.widgets.tables import (
    ACCOUNT_COLUMNS,
    ANOMALY_COLUMNS,
    VIDEO_COLUMNS,
    Column,
    DictTableModel,
    PlatformBadgeDelegate,
    configure_table,
)
from app.ui.widgets.toolbar import ToolbarRow

__all__ = [
    "AiChatPanel",
    "QUICK_QUESTIONS",
    "InsightBriefCard",
    "Badge",
    "KpiCard",
    "ModuleCard",
    "Pill",
    "SectionCard",
    "SegmentBar",
    "StatRow",
    "StatusDot",
    "build_kpi_row",
    "caption_label",
    "chip",
    "hint_label",
    "horizontal_line",
    "hstack",
    "muted_label",
    "section_label",
    "vstack",
    "FunnelBars",
    "MiniBars",
    "PlatformBarChart",
    "SentimentBar",
    "SentimentPie",
    "TopicCloud",
    "TrendChart",
    "WordCloudWidget",
    "PageScrollArea",
    "ResponsiveKpiRow",
    "ResponsiveSplitter",
    "ToolbarRow",
    "ACCOUNT_COLUMNS",
    "ANOMALY_COLUMNS",
    "VIDEO_COLUMNS",
    "Column",
    "DictTableModel",
    "PlatformBadgeDelegate",
    "configure_table",
]
